# Generated by Django 6.0.7 on 2026-08-01 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "categoría",
                "verbose_name_plural": "categorías",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Saga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "saga",
                "verbose_name_plural": "sagas",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("video", models.CharField(max_length=500)),
                ("thumbnail", models.CharField(max_length=500)),
                ("duration_sec", models.PositiveIntegerField(default=0)),
                ("order_in_saga", models.PositiveIntegerField(default=0)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="movies", to="catalog.category"
                    ),
                ),
                (
                    "saga",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movies",
                        to="catalog.saga",
                    ),
                ),
            ],
            options={
                "verbose_name": "película",
                "verbose_name_plural": "películas",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("thumbnail", models.CharField(max_length=500)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="series", to="catalog.category"
                    ),
                ),
            ],
            options={
                "verbose_name": "serie",
                "verbose_name_plural": "series",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasons",
                        to="catalog.series",
                    ),
                ),
            ],
            options={
                "verbose_name": "temporada",
                "verbose_name_plural": "temporadas",
                "ordering": ["series", "number"],
                "unique_together": {("series", "number")},
            },
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=200)),
                ("video", models.CharField(max_length=500)),
                ("thumbnail", models.CharField(blank=True, max_length=500)),
                ("duration_sec", models.PositiveIntegerField(default=0)),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        to="catalog.season",
                    ),
                ),
            ],
            options={
                "verbose_name": "episodio",
                "verbose_name_plural": "episodios",
                "ordering": ["season", "number"],
                "unique_together": {("season", "number")},
            },
        ),
    ]
